# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"\x0e\n\x0c\x45mptyMessage\"7\n\x12RequestVoteMessage\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x03\"6\n\x14\x41ppendEntriesMessage\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x10\n\x08leaderId\x18\x02 \x01(\x03\" \n\x0eSuspendMessage\x12\x0e\n\x06period\x18\x01 \x01(\x03\"-\n\x0cNodeResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\"-\n\x0eLeaderResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t2\xc8\x01\n\x04Raft\x12\x31\n\x0bRequestVote\x12\x13.RequestVoteMessage\x1a\r.NodeResponse\x12\x35\n\rAppendEntries\x12\x15.AppendEntriesMessage\x1a\r.NodeResponse\x12+\n\tGetLeader\x12\r.EmptyMessage\x1a\x0f.LeaderResponse\x12)\n\x07Suspend\x12\x0f.SuspendMessage\x1a\r.EmptyMessageb\x06proto3')



_EMPTYMESSAGE = DESCRIPTOR.message_types_by_name['EmptyMessage']
_REQUESTVOTEMESSAGE = DESCRIPTOR.message_types_by_name['RequestVoteMessage']
_APPENDENTRIESMESSAGE = DESCRIPTOR.message_types_by_name['AppendEntriesMessage']
_SUSPENDMESSAGE = DESCRIPTOR.message_types_by_name['SuspendMessage']
_NODERESPONSE = DESCRIPTOR.message_types_by_name['NodeResponse']
_LEADERRESPONSE = DESCRIPTOR.message_types_by_name['LeaderResponse']
EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMessage)
  })
_sym_db.RegisterMessage(EmptyMessage)

RequestVoteMessage = _reflection.GeneratedProtocolMessageType('RequestVoteMessage', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTVOTEMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:RequestVoteMessage)
  })
_sym_db.RegisterMessage(RequestVoteMessage)

AppendEntriesMessage = _reflection.GeneratedProtocolMessageType('AppendEntriesMessage', (_message.Message,), {
  'DESCRIPTOR' : _APPENDENTRIESMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:AppendEntriesMessage)
  })
_sym_db.RegisterMessage(AppendEntriesMessage)

SuspendMessage = _reflection.GeneratedProtocolMessageType('SuspendMessage', (_message.Message,), {
  'DESCRIPTOR' : _SUSPENDMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:SuspendMessage)
  })
_sym_db.RegisterMessage(SuspendMessage)

NodeResponse = _reflection.GeneratedProtocolMessageType('NodeResponse', (_message.Message,), {
  'DESCRIPTOR' : _NODERESPONSE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:NodeResponse)
  })
_sym_db.RegisterMessage(NodeResponse)

LeaderResponse = _reflection.GeneratedProtocolMessageType('LeaderResponse', (_message.Message,), {
  'DESCRIPTOR' : _LEADERRESPONSE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:LeaderResponse)
  })
_sym_db.RegisterMessage(LeaderResponse)

_RAFT = DESCRIPTOR.services_by_name['Raft']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYMESSAGE._serialized_start=14
  _EMPTYMESSAGE._serialized_end=28
  _REQUESTVOTEMESSAGE._serialized_start=30
  _REQUESTVOTEMESSAGE._serialized_end=85
  _APPENDENTRIESMESSAGE._serialized_start=87
  _APPENDENTRIESMESSAGE._serialized_end=141
  _SUSPENDMESSAGE._serialized_start=143
  _SUSPENDMESSAGE._serialized_end=175
  _NODERESPONSE._serialized_start=177
  _NODERESPONSE._serialized_end=222
  _LEADERRESPONSE._serialized_start=224
  _LEADERRESPONSE._serialized_end=269
  _RAFT._serialized_start=272
  _RAFT._serialized_end=472
# @@protoc_insertion_point(module_scope)
